### ISSUE TITLE
Issues faced while building

### ISSUE THREAD

**Issue by rajupara** [watson-developer-cloud/tradeoff-analytics-java#1]
Error message: 
Build Failed:
C:\xxx\xxx\xxx\build.xml:42: Problem creating war: C:\xxx\xxx\xxx\output\webApp.war (The system cannot find the path specified.) (and the archive is probably corrupt but I could not delete it).

**Comment by germanattanasio** [comment]
I can't reproduce the issue.

![screen shot 2015-03-08 at 1 53 54 am](https://cloud.githubusercontent.com/assets/313157/6544949/07b884de-c536-11e4-8bb2-f833e9e1f27f.png)
