### ISSUE TITLE
tradeoff analytics response problem

### ISSUE THREAD

**Issue by snehalkulkarni1991** [watson-developer-cloud/tradeoff-analytics-java#7]
Hello. 
I downloaded the sample code for tradeoff analytics and was trying it on my local machine. I could run the code (index.jsp) file properly. When I clicked on Analyze button the following screen showed up. I think there is some problem with the css file. Could you please guide me on this issue ? 

![github](https://cloud.githubusercontent.com/assets/12796546/8033872/e64a4dc4-0dff-11e5-8bd7-1ffb569df7da.PNG)

When I refreshed the page and clicked on Analyze again, nothing showed up . Some guidance regarding this will be a great help !

**Comment by germanattanasio** [comment]
Did you follow the steps and update the `DemoServlet.java` with the credentials? Do you see errors in the web developer console?

**Comment by snehalkulkarni1991** [comment]
Yes . I followed the steps mentioned and updated the DemoServlet.java file with the credentials. No I do not see any errors on the console. I checked the response status, it was 200 . So I think the response is proper but there is something missing in the UI part.

Got the following error while executing the code using Chrome
![chromeerror](https://cloud.githubusercontent.com/assets/12796546/8055821/e4ef9aae-0ebf-11e5-98e8-df0c0cb8cc34.PNG)

**Comment by germanattanasio** [comment]
@boazdavid do you know what is that error?

**Comment by boazdavid** [comment]
It is indeed a CSS problem.
did you pass a _customCssUrl_ in the _taClient.start()_ options? What value did you pass?
If it is a CSS generated from LESS - you may have to re-generate it according to the [new structure](http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/tradeoff-analytics/client.shtml#usingThemes) (GA version)

**Comment by watsonplatformservices** [comment]
@germanattanasio @boazdavid the problem is style sheet is being accessed over HTTP and not HTTPS in index.js

**Comment by tparikh** [comment]
@germanattanasio @boazdavid the problem is style sheet is being accessed over HTTP and not HTTPS in index.js

**Comment by germanattanasio** [comment]
Thanks @tparikh

**Comment by snehalkulkarni1991** [comment]
Thank you ! It solved my problem !!
